version: '3.7'
services:
  mysql:
    container_name: flask_mysql
    image: mysql:5.7
    volumes:
        # pass volume named mysql-data to mysql container
      - mysql-data:/var/lib/mysql
    restart: unless-stopped
    ports:
    # <Port exposed> : <MySQL Port running inside container>
      - "3307:3306"
    environment:
      # Password for root access
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: db
      MYSQL_USER: admin
      MYSQL_PASSWORD: mysql

  # Mysql Admin
  myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: flask-phpmyadmin
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=""
      - PMA_PORT=3306
    restart: always
    depends_on:
      - mysql
    links:
      - mysql

# volumes definition here
volumes:
  # just a persistance data
  mysql-data:
    driver: local